// model <modelname> <outputfilename>
$model "models/model.md3"
$parentjoint "Pelvis"
$frames 0 0
$sequence Walk 1 10
$sequence Run 11 20
$flags 0
$numskins 0

// tags <tagname> <ms3djointname>
$tag "tag_name1" "joint1"
$tag "tag_name2" "joint2"
$tag "tag_name3" "joint3"

// mesh <meshname> <ms3dgroupname>
$mesh h_head h_head 
$skin models/skin01.pcx
$flags 0

// mesh <meshname> <ms3dgroupname>
$mesh h_head h_head
$skin models/skin01.pcx
$flags 0